### ISSUE TITLE
File refreshed to top of file

### ISSUE THREAD

**Issue by VitaeEssence** [LukasCernySC/TemplateStudioRelease#13]
File refreshes/resets to top of file if you click on another tabbed/open file. See below for better explanation.

![1](https://user-images.githubusercontent.com/53269751/180909329-7f9bebd9-801e-41a6-b1ec-3eb1afae2214.png)

![2](https://user-images.githubusercontent.com/53269751/180909332-12dd3aca-6963-43e9-804a-137463111451.png)

![3](https://user-images.githubusercontent.com/53269751/180909334-67bd2154-41ca-4355-ba77-afa62af7d097.png)

**Comment by LukasCernySC** [comment]
Fixed for version 1.0.9
